const output1 = {
  sprints: [
    [
      {
        assignedDeveloperId: 1,
        dependencies: [],
        developers: [
          { id: 1, name: 'mukul' },
          { id: 2, name: 'sahil' },
        ],
        duration: 6,
        endDay: 3,
        id: 4,
        remainingDuration: 0,
        startDay: 0,
      },
      {
        assignedDeveloperId: 0,
        dependencies: [],
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
          { id: 2, name: 'sahil' },
        ],
        duration: 5,
        endDay: 4,
        id: 5,
        remainingDuration: -1,
        startDay: 0,
      },
      {
        assignedDeveloperId: 0,
        dependencies: [4, 5],
        developers: [
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
        ],
        duration: 5,
        endDay: 7,
        id: 0,
        remainingDuration: -1,
        startDay: 4,
      },
      {
        assignedDeveloperId: 1,
        dependencies: [5],
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
        ],
        duration: 4,
        endDay: 8,
        id: 2,
        remainingDuration: -2,
        startDay: 4,
      },
      {
        assignedDeveloperId: 1,
        dependencies: [2],
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
        ],
        duration: 2,
        endDay: 9,
        id: 3,
        remainingDuration: -1,
        startDay: 8,
      },
      {
        assignedDeveloperId: 1,
        dependencies: [3, 4],
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
        ],
        duration: 3,
        endDay: 10,
        id: 1,
        remainingDuration: 0,
        startDay: 9,
      },
    ],
  ],
};
const output2 = {
  sprints: [
    [
      {
        id: 4,
        dependencies: [],
        duration: 6,
        assignedDeveloperId: 0,
        startDay: 0,
        endDay: 6,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 5,
        dependencies: [],
        duration: 5,
        assignedDeveloperId: 1,
        startDay: 0,
        endDay: 5,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
      {
        id: 2,
        dependencies: [5],
        duration: 4,
        assignedDeveloperId: 1,
        startDay: 5,
        endDay: 9,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
      {
        id: 0,
        dependencies: [4, 5],
        duration: 5,
        assignedDeveloperId: 0,
        startDay: 6,
        endDay: 11,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 3,
        dependencies: [2],
        duration: 2,
        assignedDeveloperId: 1,
        startDay: 9,
        endDay: 11,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
    ],
    [
      {
        id: 0,
        dependencies: [4, 5],
        duration: 5,
        assignedDeveloperId: 0,
        startDay: 6,
        endDay: 11,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 3,
        dependencies: [2],
        duration: 2,
        assignedDeveloperId: 1,
        startDay: 9,
        endDay: 11,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
      {
        id: 1,
        dependencies: [3, 4],
        duration: 3,
        assignedDeveloperId: 0,
        startDay: 11,
        endDay: 13,
        remainingDuration: -1,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
        ],
      },
    ],
  ],
};
const output3 = {
  sprints: [
    [
      {
        id: 4,
        dependencies: [],
        duration: 5,
        assignedDeveloperId: 1,
        startDay: 0,
        endDay: 5,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
      {
        id: 5,
        dependencies: [],
        duration: 6,
        assignedDeveloperId: 0,
        startDay: 0,
        endDay: 6,
        remainingDuration: -1,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
        ],
      },
      {
        id: 0,
        dependencies: [4, 5],
        duration: 5,
        assignedDeveloperId: 0,
        startDay: 6,
        endDay: 11,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 2,
        dependencies: [5],
        duration: 4,
        assignedDeveloperId: 1,
        startDay: 6,
        endDay: 10,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
    ],
    [
      {
        id: 0,
        dependencies: [4, 5],
        duration: 5,
        assignedDeveloperId: 0,
        startDay: 6,
        endDay: 11,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 3,
        dependencies: [2],
        duration: 2,
        assignedDeveloperId: 1,
        startDay: 10,
        endDay: 12,
        remainingDuration: -1,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
        ],
      },
      {
        id: 1,
        dependencies: [3, 4],
        duration: 3,
        assignedDeveloperId: 1,
        startDay: 12,
        endDay: 14,
        remainingDuration: -1,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
        ],
      },
    ],
  ],
};
const output4 = {
  sprints: [
    [
      {
        id: 4,
        dependencies: [],
        duration: 5,
        assignedDeveloperId: 1,
        startDay: 0,
        endDay: 3,
        remainingDuration: -1,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 2, name: 'sahil' },
        ],
      },
      {
        id: 5,
        dependencies: [],
        duration: 6,
        assignedDeveloperId: 0,
        startDay: 0,
        endDay: 4,
        remainingDuration: 0,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
          { id: 2, name: 'sahil' },
        ],
      },
      {
        id: 0,
        dependencies: [4, 5],
        duration: 5,
        assignedDeveloperId: 0,
        startDay: 4,
        endDay: 7,
        remainingDuration: -1,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
        ],
      },
      {
        id: 2,
        dependencies: [5],
        duration: 4,
        assignedDeveloperId: 1,
        startDay: 4,
        endDay: 8,
        remainingDuration: -2,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
        ],
      },
      {
        id: 3,
        dependencies: [2],
        duration: 2,
        assignedDeveloperId: 1,
        startDay: 8,
        endDay: 9,
        remainingDuration: -1,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
        ],
      },
      {
        id: 1,
        dependencies: [3, 4],
        duration: 3,
        assignedDeveloperId: 1,
        startDay: 9,
        endDay: 10,
        remainingDuration: 0,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
        ],
      },
    ],
  ],
};
const output5 = {
  err: 'Cycle detected in dependencies',
};
const output6 = {
  sprints: [
    [
      {
        id: 4,
        dependencies: [],
        duration: 6,
        assignedDeveloperId: 0,
        startDay: 0,
        endDay: 3,
        remainingDuration: 0,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
        ],
      },
      {
        id: 5,
        dependencies: [],
        duration: 5,
        assignedDeveloperId: 2,
        startDay: 0,
        endDay: 4,
        remainingDuration: -1,
        developers: [
          { id: 2, name: 'sahil' },
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
        ],
      },
      {
        id: 0,
        dependencies: [4, 5],
        duration: 5,
        assignedDeveloperId: 2,
        startDay: 4,
        endDay: 7,
        remainingDuration: -1,
        developers: [
          { id: 2, name: 'sahil' },
          { id: 1, name: 'mukul' },
        ],
      },
      {
        id: 2,
        dependencies: [5],
        duration: 4,
        assignedDeveloperId: 0,
        startDay: 4,
        endDay: 8,
        remainingDuration: -2,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
          { id: 1, name: 'mukul' },
        ],
      },
      {
        id: 3,
        dependencies: [2],
        duration: 2,
        assignedDeveloperId: 0,
        startDay: 8,
        endDay: 9,
        remainingDuration: -1,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
          { id: 1, name: 'mukul' },
        ],
      },
      {
        id: 1,
        dependencies: [3, 4],
        duration: 3,
        assignedDeveloperId: 0,
        startDay: 9,
        endDay: 10,
        remainingDuration: 0,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
          { id: 1, name: 'mukul' },
        ],
      },
    ],
  ],
};
const output7 = {
  sprints: [
    [
      {
        id: 1,
        dependencies: [],
        duration: 6,
        assignedDeveloperId: 1,
        startDay: 0,
        endDay: 6,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
      {
        id: 2,
        dependencies: [],
        duration: 2,
        assignedDeveloperId: 0,
        startDay: 0,
        endDay: 2,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 3,
        dependencies: [],
        duration: 3,
        assignedDeveloperId: 2,
        startDay: 0,
        endDay: 3,
        remainingDuration: 0,
        developers: [{ id: 2, name: 'sahil' }],
      },
      {
        id: 0,
        dependencies: [2],
        duration: 5,
        assignedDeveloperId: 0,
        startDay: 2,
        endDay: 7,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 4,
        dependencies: [],
        duration: 5,
        assignedDeveloperId: 2,
        startDay: 3,
        endDay: 8,
        remainingDuration: 0,
        developers: [{ id: 2, name: 'sahil' }],
      },
      {
        id: 5,
        dependencies: [],
        duration: 4,
        assignedDeveloperId: 1,
        startDay: 6,
        endDay: 10,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
      {
        id: 6,
        dependencies: [],
        duration: 3,
        assignedDeveloperId: 0,
        startDay: 7,
        endDay: 10,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 7,
        dependencies: [],
        duration: 5,
        assignedDeveloperId: 2,
        startDay: 8,
        endDay: 12,
        remainingDuration: -1,
        developers: [
          { id: 2, name: 'sahil' },
          { id: 0, name: 'harbir' },
        ],
      },
    ],
    [
      {
        id: 7,
        dependencies: [],
        duration: 5,
        assignedDeveloperId: 2,
        startDay: 8,
        endDay: 12,
        remainingDuration: -1,
        developers: [
          { id: 2, name: 'sahil' },
          { id: 0, name: 'harbir' },
        ],
      },
      {
        id: 8,
        dependencies: [],
        duration: 6,
        assignedDeveloperId: 1,
        startDay: 10,
        endDay: 14,
        remainingDuration: -2,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 2, name: 'sahil' },
          { id: 0, name: 'harbir' },
        ],
      },
    ],
  ],
};
const output8 = {
  sprints: [
    [
      {
        id: 0,
        dependencies: [],
        duration: 5,
        assignedDeveloperId: 0,
        startDay: 0,
        endDay: 5,
        remainingDuration: -1,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
        ],
      },
      {
        id: 1,
        dependencies: [],
        duration: 4,
        assignedDeveloperId: 1,
        startDay: 0,
        endDay: 4,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
      {
        id: 2,
        dependencies: [0, 1],
        duration: 5,
        assignedDeveloperId: 0,
        startDay: 5,
        endDay: 9,
        remainingDuration: 0,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
        ],
      },
      {
        id: 4,
        dependencies: [0],
        duration: 3,
        assignedDeveloperId: 1,
        startDay: 5,
        endDay: 8,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
      {
        id: 3,
        dependencies: [1, 2],
        duration: 6,
        assignedDeveloperId: 0,
        startDay: 9,
        endDay: 14,
        remainingDuration: 0,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
        ],
      },
      {
        id: 5,
        dependencies: [2, 4],
        duration: 4,
        assignedDeveloperId: 1,
        startDay: 9,
        endDay: 13,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
    ],
    [
      {
        id: 3,
        dependencies: [1, 2],
        duration: 6,
        assignedDeveloperId: 0,
        startDay: 9,
        endDay: 14,
        remainingDuration: 0,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
        ],
      },
      {
        id: 5,
        dependencies: [2, 4],
        duration: 4,
        assignedDeveloperId: 1,
        startDay: 9,
        endDay: 13,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
      {
        id: 6,
        dependencies: [0, 2, 3],
        duration: 3,
        assignedDeveloperId: 0,
        startDay: 14,
        endDay: 16,
        remainingDuration: -1,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
        ],
      },
      {
        id: 7,
        dependencies: [6],
        duration: 6,
        assignedDeveloperId: 0,
        startDay: 16,
        endDay: 19,
        remainingDuration: 0,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
        ],
      },
    ],
  ],
};
const output9 = {
  sprints: [
    [
      {
        id: 3,
        dependencies: [],
        duration: 6,
        assignedDeveloperId: 1,
        startDay: 0,
        endDay: 3,
        remainingDuration: 0,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 2, name: 'sahil' },
        ],
      },
      {
        id: 4,
        dependencies: [],
        duration: 5,
        assignedDeveloperId: 0,
        startDay: 0,
        endDay: 5,
        remainingDuration: -2,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
          { id: 2, name: 'sahil' },
        ],
      },
      {
        id: 1,
        dependencies: [3],
        duration: 1,
        assignedDeveloperId: 1,
        startDay: 3,
        endDay: 4,
        remainingDuration: -1,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 2, name: 'sahil' },
        ],
      },
      {
        id: 0,
        dependencies: [4, 3],
        duration: 4,
        assignedDeveloperId: 0,
        startDay: 5,
        endDay: 7,
        remainingDuration: 0,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
        ],
      },
      {
        id: 2,
        dependencies: [3, 4],
        duration: 3,
        assignedDeveloperId: 1,
        startDay: 5,
        endDay: 8,
        remainingDuration: -2,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
        ],
      },
    ],
  ],
};
const output10 = {
  sprints: [
    [
      {
        id: 4,
        dependencies: [],
        duration: 5,
        startDay: 0,
        endDay: 3,
        remainingDuration: -1,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 2, name: 'sahil' },
        ],
        assignedDeveloperId: 1,
      },
      {
        id: 5,
        dependencies: [],
        duration: 6,
        startDay: 0,
        endDay: 4,
        remainingDuration: 0,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
          { id: 2, name: 'sahil' },
        ],
        assignedDeveloperId: 0,
      },
      {
        id: 0,
        dependencies: [4, 5],
        duration: 4,
        startDay: 4,
        endDay: 7,
        remainingDuration: -1,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
        ],
        assignedDeveloperId: 0,
      },
      {
        id: 1,
        dependencies: [5],
        duration: 1,
        startDay: 4,
        endDay: 5,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
        assignedDeveloperId: 1,
      },
      {
        id: 2,
        dependencies: [4, 5],
        duration: 3,
        startDay: 4,
        endDay: 7,
        remainingDuration: 0,
        developers: [{ id: 2, name: 'sahil' }],
        assignedDeveloperId: 2,
      },
      {
        id: 3,
        dependencies: [0],
        duration: 2,
        startDay: 7,
        endDay: 8,
        remainingDuration: -1,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
          { id: 2, name: 'sahil' },
        ],
        assignedDeveloperId: 0,
      },
    ],
  ],
};
const output11 = {
  sprints: [
    [
      {
        id: 0,
        dependencies: [],
        duration: 3,
        assignedDeveloperId: 0,
        startDay: 0,
        endDay: 3,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 3,
        dependencies: [],
        duration: 4,
        assignedDeveloperId: 1,
        startDay: 0,
        endDay: 4,
        remainingDuration: -1,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
        ],
      },
      {
        id: 5,
        dependencies: [],
        duration: 11,
        assignedDeveloperId: 2,
        startDay: 0,
        endDay: 9,
        remainingDuration: -2,
        developers: [
          { id: 2, name: 'sahil' },
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
        ],
      },
      {
        id: 1,
        dependencies: [0, 3],
        duration: 6,
        assignedDeveloperId: 1,
        startDay: 4,
        endDay: 7,
        remainingDuration: 0,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
        ],
      },
      {
        id: 2,
        dependencies: [1, 5],
        duration: 5,
        assignedDeveloperId: 2,
        startDay: 9,
        endDay: 12,
        remainingDuration: -1,
        developers: [
          { id: 2, name: 'sahil' },
          { id: 0, name: 'harbir' },
        ],
      },
      {
        id: 4,
        dependencies: [1, 5],
        duration: 3,
        assignedDeveloperId: 1,
        startDay: 9,
        endDay: 12,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
    ],
    [
      {
        id: 2,
        dependencies: [1, 5],
        duration: 5,
        assignedDeveloperId: 2,
        startDay: 9,
        endDay: 12,
        remainingDuration: -1,
        developers: [
          { id: 2, name: 'sahil' },
          { id: 0, name: 'harbir' },
        ],
      },
      {
        id: 4,
        dependencies: [1, 5],
        duration: 3,
        assignedDeveloperId: 1,
        startDay: 9,
        endDay: 12,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
    ],
  ],
};
const output12 = {
  sprints: [
    [
      {
        id: 0,
        dependencies: [],
        duration: 3,
        assignedDeveloperId: 0,
        startDay: 0,
        endDay: 3,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 3,
        dependencies: [],
        duration: 4,
        assignedDeveloperId: 1,
        startDay: 0,
        endDay: 4,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
      {
        id: 5,
        dependencies: [],
        duration: 11,
        assignedDeveloperId: 0,
        startDay: 3,
        endDay: 12,
        remainingDuration: 0,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
        ],
      },
      {
        id: 1,
        dependencies: [0, 3],
        duration: 6,
        assignedDeveloperId: 1,
        startDay: 4,
        endDay: 10,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
    ],
    [
      {
        id: 5,
        dependencies: [],
        duration: 11,
        assignedDeveloperId: 0,
        startDay: 3,
        endDay: 12,
        remainingDuration: 0,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
        ],
      },
      {
        id: 2,
        dependencies: [1, 5],
        duration: 5,
        assignedDeveloperId: 0,
        startDay: 12,
        endDay: 16,
        remainingDuration: 0,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
        ],
      },
      {
        id: 4,
        dependencies: [1, 5],
        duration: 3,
        assignedDeveloperId: 1,
        startDay: 12,
        endDay: 15,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
    ],
  ],
};
const output13 = {
  sprints: [
    [
      {
        id: 0,
        dependencies: [],
        duration: 3,
        assignedDeveloperId: 0,
        startDay: 0,
        endDay: 3,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 3,
        dependencies: [],
        duration: 4,
        assignedDeveloperId: 0,
        startDay: 3,
        endDay: 7,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 1,
        dependencies: [0, 3],
        duration: 6,
        assignedDeveloperId: 0,
        startDay: 7,
        endDay: 13,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
    ],
    [
      {
        id: 1,
        dependencies: [0, 3],
        duration: 6,
        assignedDeveloperId: 0,
        startDay: 7,
        endDay: 13,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 5,
        dependencies: [],
        duration: 11,
        assignedDeveloperId: 0,
        startDay: 13,
        endDay: 24,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
    ],
    [
      {
        id: 5,
        dependencies: [],
        duration: 11,
        assignedDeveloperId: 0,
        startDay: 13,
        endDay: 24,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 2,
        dependencies: [1, 5],
        duration: 5,
        assignedDeveloperId: 0,
        startDay: 24,
        endDay: 29,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 4,
        dependencies: [1, 5],
        duration: 3,
        assignedDeveloperId: 0,
        startDay: 29,
        endDay: 32,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
    ],
    [
      {
        id: 4,
        dependencies: [1, 5],
        duration: 3,
        assignedDeveloperId: 0,
        startDay: 29,
        endDay: 32,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
    ],
  ],
};

const output14 = {
  sprints: [
    [
      {
        id: 0,
        dependencies: [],
        duration: 3,
        assignedDeveloperId: 0,
        startDay: 0,
        endDay: 2,
        remainingDuration: -1,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 3, name: 'ram' },
        ],
      },
      {
        id: 3,
        dependencies: [],
        duration: 4,
        assignedDeveloperId: 1,
        startDay: 0,
        endDay: 3,
        remainingDuration: -1,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
          { id: 3, name: 'ram' },
        ],
      },
      {
        id: 5,
        dependencies: [],
        duration: 11,
        assignedDeveloperId: 2,
        startDay: 0,
        endDay: 7,
        remainingDuration: -2,
        developers: [
          { id: 2, name: 'sahil' },
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
          { id: 3, name: 'ram' },
        ],
      },
      {
        id: 1,
        dependencies: [0, 3],
        duration: 6,
        assignedDeveloperId: 1,
        startDay: 3,
        endDay: 5,
        remainingDuration: 0,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
          { id: 3, name: 'ram' },
        ],
      },
      {
        id: 2,
        dependencies: [1, 5],
        duration: 5,
        assignedDeveloperId: 2,
        startDay: 7,
        endDay: 9,
        remainingDuration: -1,
        developers: [
          { id: 2, name: 'sahil' },
          { id: 0, name: 'harbir' },
          { id: 3, name: 'ram' },
        ],
      },
      {
        id: 4,
        dependencies: [1, 5],
        duration: 3,
        assignedDeveloperId: 1,
        startDay: 7,
        endDay: 10,
        remainingDuration: -3,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 2, name: 'sahil' },
          { id: 0, name: 'harbir' },
          { id: 3, name: 'ram' },
        ],
      },
    ],
  ],
};
const output15 = {
  sprints: [
    [
      {
        id: 3,
        dependencies: [],
        duration: 8,
        assignedDeveloperId: 0,
        startDay: 0,
        endDay: 3,
        remainingDuration: -1,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
          { id: 1, name: 'mukul' },
        ],
      },
      {
        id: 1,
        dependencies: [3],
        duration: 6,
        assignedDeveloperId: 0,
        startDay: 3,
        endDay: 6,
        remainingDuration: -1,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
          { id: 2, name: 'sahil' },
        ],
      },
      {
        id: 4,
        dependencies: [3],
        duration: 2,
        assignedDeveloperId: 2,
        startDay: 3,
        endDay: 5,
        remainingDuration: 0,
        developers: [{ id: 2, name: 'sahil' }],
      },
      {
        id: 0,
        dependencies: [1],
        duration: 5,
        assignedDeveloperId: 0,
        startDay: 6,
        endDay: 9,
        remainingDuration: -1,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
        ],
      },
      {
        id: 2,
        dependencies: [1, 3],
        duration: 9,
        assignedDeveloperId: 1,
        startDay: 6,
        endDay: 11,
        remainingDuration: 0,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
        ],
      },
    ],
    [
      {
        id: 2,
        dependencies: [1, 3],
        duration: 9,
        assignedDeveloperId: 1,
        startDay: 6,
        endDay: 11,
        remainingDuration: 0,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
        ],
      },
    ],
  ],
};
const output16 = {
  sprints: [
    [
      {
        id: 3,
        dependencies: [],
        duration: 8,
        assignedDeveloperId: 0,
        startDay: 0,
        endDay: 4,
        remainingDuration: 0,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
        ],
      },
      {
        id: 1,
        dependencies: [3],
        duration: 6,
        assignedDeveloperId: 0,
        startDay: 4,
        endDay: 8,
        remainingDuration: 0,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
        ],
      },
      {
        id: 4,
        dependencies: [3],
        duration: 2,
        assignedDeveloperId: 1,
        startDay: 4,
        endDay: 6,
        remainingDuration: 0,
        developers: [{ id: 1, name: 'mukul' }],
      },
      {
        id: 0,
        dependencies: [1],
        duration: 5,
        assignedDeveloperId: 0,
        startDay: 8,
        endDay: 13,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 2,
        dependencies: [1, 3],
        duration: 9,
        assignedDeveloperId: 1,
        startDay: 8,
        endDay: 15,
        remainingDuration: 0,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
        ],
      },
    ],
    [
      {
        id: 0,
        dependencies: [1],
        duration: 5,
        assignedDeveloperId: 0,
        startDay: 8,
        endDay: 13,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 2,
        dependencies: [1, 3],
        duration: 9,
        assignedDeveloperId: 1,
        startDay: 8,
        endDay: 15,
        remainingDuration: 0,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
        ],
      },
    ],
  ],
};
const output17 = {
  sprints: [
    [
      {
        id: 3,
        dependencies: [],
        duration: 8,
        assignedDeveloperId: 0,
        startDay: 0,
        endDay: 2,
        remainingDuration: 0,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 2, name: 'sahil' },
          { id: 1, name: 'mukul' },
          { id: 3, name: 'ram' },
        ],
      },
      {
        id: 1,
        dependencies: [3],
        duration: 6,
        assignedDeveloperId: 0,
        startDay: 2,
        endDay: 4,
        remainingDuration: 0,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 1, name: 'mukul' },
          { id: 3, name: 'ram' },
        ],
      },
      {
        id: 4,
        dependencies: [3],
        duration: 2,
        assignedDeveloperId: 2,
        startDay: 2,
        endDay: 4,
        remainingDuration: 0,
        developers: [{ id: 2, name: 'sahil' }],
      },
      {
        id: 0,
        dependencies: [1],
        duration: 5,
        assignedDeveloperId: 0,
        startDay: 4,
        endDay: 6,
        remainingDuration: -1,
        developers: [
          { id: 0, name: 'harbir' },
          { id: 3, name: 'ram' },
          { id: 2, name: 'sahil' },
        ],
      },
      {
        id: 2,
        dependencies: [1, 3],
        duration: 9,
        assignedDeveloperId: 1,
        startDay: 4,
        endDay: 8,
        remainingDuration: -1,
        developers: [
          { id: 1, name: 'mukul' },
          { id: 0, name: 'harbir' },
          { id: 3, name: 'ram' },
          { id: 2, name: 'sahil' },
        ],
      },
    ],
  ],
};
const output18 = { err: 'No stories available' };
const output19 = { err: 'No developers available' };

const output20 = {
  sprints: [
    [
      {
        id: 0,
        dependencies: [],
        duration: 3,
        assignedDeveloperId: 0,
        startDay: 0,
        endDay: 3,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 3,
        dependencies: [],
        duration: 4,
        assignedDeveloperId: 0,
        startDay: 3,
        endDay: 7,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 1,
        dependencies: [0, 3],
        duration: 6,
        assignedDeveloperId: 0,
        startDay: 7,
        endDay: 13,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 5,
        dependencies: [],
        duration: 11,
        assignedDeveloperId: 0,
        startDay: 13,
        endDay: 24,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
    ],
    [
      {
        id: 5,
        dependencies: [],
        duration: 11,
        assignedDeveloperId: 0,
        startDay: 13,
        endDay: 24,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 2,
        dependencies: [1, 5],
        duration: 5,
        assignedDeveloperId: 0,
        startDay: 24,
        endDay: 29,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
      {
        id: 4,
        dependencies: [1, 5],
        duration: 3,
        assignedDeveloperId: 0,
        startDay: 29,
        endDay: 32,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
    ],
    [
      {
        id: 4,
        dependencies: [1, 5],
        duration: 3,
        assignedDeveloperId: 0,
        startDay: 29,
        endDay: 32,
        remainingDuration: 0,
        developers: [{ id: 0, name: 'harbir' }],
      },
    ],
  ],
};

const outputs = {
  output1,
  output2,
  output3,
  output4,
  output5,
  output6,
  output7,
  output8,
  output9,
  output10,
  output11,
  output12,
  output13,
  output14,
  output15,
  output16,
  output17,
  output18,
  output19,
  output20,
};
module.exports = outputs;
